language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - redis-server

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
      - php: hhvm

install: travis_retry composer install

script: vendor/bin/phpunit --verbose
