language: php

php:
  - 5.5
  - 5.6
  - 7.0

services:
  - redis-server

branches:
  only:
    - master

matrix:
  fast_finish: true

install: travis_retry composer install

script: vendor/bin/phpunit --verbose
